name: Deploy release to Chocolatey

on:
  release:
    types: [published]

jobs:
  deploy-to-choco:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
